name: Feature
description: Feature derived from an MXL Requirement
labels:
  - Feature
assignees: []
title: "[Feature] <short description>"

body:
  - type: input
    id: requirement_link
    attributes:
      label: Requirement Link
      description: >
        Link or number of the related requirement in the MXL Requirements repo.
        Accepted formats: `12345`, `#12345`, `dmf-mxl/mxl-requirements#12345`, or a full URL.
      placeholder: "12345"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear, concise description of the feature.
      placeholder: "Describe the feature"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, background information, or images.
      placeholder: "Include relevant background, links, screenshots, or diagrams."
    validations:
      required: false

# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0
